# Generated by Django 4.1.1 on 2022-11-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Experiencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrimeraApp.experiencias')),
            ],
        ),
    ]
