# Generated by Django 4.1.1 on 2022-11-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0007_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='experiencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PrimeraApp.experiencias'),
            preserve_default=False,
        ),
    ]
