# Generated by Django 4.1.1 on 2022-11-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0008_usuarios_experiencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencias',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='experiencias',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='mensaje',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
