# Generated by Django 4.1.1 on 2022-11-04 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0009_remove_experiencias_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='experiencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PrimeraApp.experiencias'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='mensaje',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
