# Generated by Django 4.1.1 on 2022-11-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0010_alter_usuarios_experiencia_alter_usuarios_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eliminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
