# Generated by Django 4.1.1 on 2022-11-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0011_eliminar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eliminar',
        ),
        migrations.AddField(
            model_name='experiencias',
            name='mensaje',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
