# Generated by Django 4.1.1 on 2022-11-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0008_product'),
        ('PrimeraApp', '0012_delete_eliminar_experiencias_mensaje_delete_usuarios'),
    ]

    operations = [
    ]
