# Generated by Django 4.1.1 on 2022-11-14 01:37

import PrimeraApp.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0014_crud_usuarios_delete_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencias',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crud',
            name='objeto',
            field=models.CharField(choices=[(PrimeraApp.models.Experiencias, 'Experiencias'), (PrimeraApp.models.Usuarios, 'usuarios')], max_length=50),
        ),
    ]
