# Generated by Django 4.1.1 on 2022-11-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeraApp', '0015_experiencias_fecha_alter_crud_objeto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Basic', 'Basico'), ('Intermediate', 'Intermedio'), ('Advanced', 'Avanzado')], max_length=50)),
                ('duracion', models.CharField(choices=[(6, '6 meses'), (4, '4 meses'), (3, '3 meses')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Crud',
        ),
    ]
